### ISSUE TITLE
[Front] Tela de criar um projeto

### ISSUE THREAD

**Issue by vitor-rc1** [Univesp-PIs/DRP04-PJI240-FRONT#6]
[Figma](https://www.figma.com/design/0rYkBqfzQMpOebOK9w4swA/PI2-Order-Status?node-id=2327-53&t=Xqz04jiCfg4MvxQh-4)

## Checklist
- [x] inserir header (logo)
- [x] Criar campos para o cadastro do projeto
- [x] Adicionar Inputs da linha do tempo.
- [x] Ao carregar a tela deve adicionar uma linha do tempo defaul
- [ ] Adicionar requisição para a rota `project` do tipo `POST`
- [ ] Deve usar os ids que retornam da rota `status` do tipo `GET` para compor a linha do tempo

## Contrato de requisição

````
{
    "email": "email do usuario",
    "project_name": "Projeto-1234",
    "timelime": [
        {
            "id": "7",
            "rank": 0, // é o que definie a ordem de inserção
            "name": "Entrega dos documentos" 
        },
        ...
    ]
}
````
## Contrato de resposta
Code 201: Created
Body: Vazio (Não precisa retornar nada)

**Comment by GabrielRibeiro19** [comment]
Está pronto, falta só consumir a api e fazer o post pro backend salvar
